#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorUploadService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClaimStakerDEV")]
	public partial class TestDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClaimMedicalBase_T(ClaimMedicalBase_T instance);
    partial void UpdateClaimMedicalBase_T(ClaimMedicalBase_T instance);
    partial void DeleteClaimMedicalBase_T(ClaimMedicalBase_T instance);
    partial void InsertClaimMedicalClaimInformation_T(ClaimMedicalClaimInformation_T instance);
    partial void UpdateClaimMedicalClaimInformation_T(ClaimMedicalClaimInformation_T instance);
    partial void DeleteClaimMedicalClaimInformation_T(ClaimMedicalClaimInformation_T instance);
    #endregion
		
		public TestDatabaseDataContext() : 
				base(global::VendorUploadService.Properties.Settings.Default.ClaimStakerDEVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TestDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClaimMedicalBase_T> ClaimMedicalBase_Ts
		{
			get
			{
				return this.GetTable<ClaimMedicalBase_T>();
			}
		}
		
		public System.Data.Linq.Table<ClaimMedicalClaimInformation_T> ClaimMedicalClaimInformation_Ts
		{
			get
			{
				return this.GetTable<ClaimMedicalClaimInformation_T>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClaimMedicalBase_T")]
	public partial class ClaimMedicalBase_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ClaimMedicalBase_ID;
		
		private System.Nullable<int> _ClaimMedicalBillingProvider_ID;
		
		private System.Nullable<int> _Provider_ID;
		
		private System.Nullable<long> _ClaimMedicalPayer_ID;
		
		private System.Nullable<int> _Payer_ID;
		
		private System.Nullable<int> _OutputSub_ID;
		
		private int _ClaimStatusType_ID;
		
		private string _BatchNumber_VC;
		
		private System.Nullable<System.DateTime> _ReportDate_DT;
		
		private string _NPI_VC;
		
		private System.Nullable<System.DateTime> _LastProcessDate_DT;
		
		private string _ClientID_VC;
		
		private System.Nullable<long> _LegacyClaim_ID;
		
		private System.DateTime _LastUpdateDate_DT;
		
		private bool _IsNoCharge_BT;
		
		private bool _IsProcessNow_BT;
		
		private string _InternalNotes_VC;
		
		private string _ApexPayerID_VC;
		
		private string _ClaimVendorID_VC;
		
		private System.Nullable<int> _EventPhase_ID;
		
		private System.Nullable<long> _EventType_ID;
		
		private System.Nullable<int> _Vendor_ID;
		
		private EntitySet<ClaimMedicalClaimInformation_T> _ClaimMedicalClaimInformation_Ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClaimMedicalBase_IDChanging(long value);
    partial void OnClaimMedicalBase_IDChanged();
    partial void OnClaimMedicalBillingProvider_IDChanging(System.Nullable<int> value);
    partial void OnClaimMedicalBillingProvider_IDChanged();
    partial void OnProvider_IDChanging(System.Nullable<int> value);
    partial void OnProvider_IDChanged();
    partial void OnClaimMedicalPayer_IDChanging(System.Nullable<long> value);
    partial void OnClaimMedicalPayer_IDChanged();
    partial void OnPayer_IDChanging(System.Nullable<int> value);
    partial void OnPayer_IDChanged();
    partial void OnOutputSub_IDChanging(System.Nullable<int> value);
    partial void OnOutputSub_IDChanged();
    partial void OnClaimStatusType_IDChanging(int value);
    partial void OnClaimStatusType_IDChanged();
    partial void OnBatchNumber_VCChanging(string value);
    partial void OnBatchNumber_VCChanged();
    partial void OnReportDate_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnReportDate_DTChanged();
    partial void OnNPI_VCChanging(string value);
    partial void OnNPI_VCChanged();
    partial void OnLastProcessDate_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnLastProcessDate_DTChanged();
    partial void OnClientID_VCChanging(string value);
    partial void OnClientID_VCChanged();
    partial void OnLegacyClaim_IDChanging(System.Nullable<long> value);
    partial void OnLegacyClaim_IDChanged();
    partial void OnLastUpdateDate_DTChanging(System.DateTime value);
    partial void OnLastUpdateDate_DTChanged();
    partial void OnIsNoCharge_BTChanging(bool value);
    partial void OnIsNoCharge_BTChanged();
    partial void OnIsProcessNow_BTChanging(bool value);
    partial void OnIsProcessNow_BTChanged();
    partial void OnInternalNotes_VCChanging(string value);
    partial void OnInternalNotes_VCChanged();
    partial void OnApexPayerID_VCChanging(string value);
    partial void OnApexPayerID_VCChanged();
    partial void OnClaimVendorID_VCChanging(string value);
    partial void OnClaimVendorID_VCChanged();
    partial void OnEventPhase_IDChanging(System.Nullable<int> value);
    partial void OnEventPhase_IDChanged();
    partial void OnEventType_IDChanging(System.Nullable<long> value);
    partial void OnEventType_IDChanged();
    partial void OnVendor_IDChanging(System.Nullable<int> value);
    partial void OnVendor_IDChanged();
    #endregion
		
		public ClaimMedicalBase_T()
		{
			this._ClaimMedicalClaimInformation_Ts = new EntitySet<ClaimMedicalClaimInformation_T>(new Action<ClaimMedicalClaimInformation_T>(this.attach_ClaimMedicalClaimInformation_Ts), new Action<ClaimMedicalClaimInformation_T>(this.detach_ClaimMedicalClaimInformation_Ts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalBase_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ClaimMedicalBase_ID
		{
			get
			{
				return this._ClaimMedicalBase_ID;
			}
			set
			{
				if ((this._ClaimMedicalBase_ID != value))
				{
					this.OnClaimMedicalBase_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalBase_ID = value;
					this.SendPropertyChanged("ClaimMedicalBase_ID");
					this.OnClaimMedicalBase_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalBillingProvider_ID", DbType="Int")]
		public System.Nullable<int> ClaimMedicalBillingProvider_ID
		{
			get
			{
				return this._ClaimMedicalBillingProvider_ID;
			}
			set
			{
				if ((this._ClaimMedicalBillingProvider_ID != value))
				{
					this.OnClaimMedicalBillingProvider_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalBillingProvider_ID = value;
					this.SendPropertyChanged("ClaimMedicalBillingProvider_ID");
					this.OnClaimMedicalBillingProvider_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_ID", DbType="Int")]
		public System.Nullable<int> Provider_ID
		{
			get
			{
				return this._Provider_ID;
			}
			set
			{
				if ((this._Provider_ID != value))
				{
					this.OnProvider_IDChanging(value);
					this.SendPropertyChanging();
					this._Provider_ID = value;
					this.SendPropertyChanged("Provider_ID");
					this.OnProvider_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalPayer_ID", DbType="BigInt")]
		public System.Nullable<long> ClaimMedicalPayer_ID
		{
			get
			{
				return this._ClaimMedicalPayer_ID;
			}
			set
			{
				if ((this._ClaimMedicalPayer_ID != value))
				{
					this.OnClaimMedicalPayer_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalPayer_ID = value;
					this.SendPropertyChanged("ClaimMedicalPayer_ID");
					this.OnClaimMedicalPayer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payer_ID", DbType="Int")]
		public System.Nullable<int> Payer_ID
		{
			get
			{
				return this._Payer_ID;
			}
			set
			{
				if ((this._Payer_ID != value))
				{
					this.OnPayer_IDChanging(value);
					this.SendPropertyChanging();
					this._Payer_ID = value;
					this.SendPropertyChanged("Payer_ID");
					this.OnPayer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutputSub_ID", DbType="Int")]
		public System.Nullable<int> OutputSub_ID
		{
			get
			{
				return this._OutputSub_ID;
			}
			set
			{
				if ((this._OutputSub_ID != value))
				{
					this.OnOutputSub_IDChanging(value);
					this.SendPropertyChanging();
					this._OutputSub_ID = value;
					this.SendPropertyChanged("OutputSub_ID");
					this.OnOutputSub_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimStatusType_ID", DbType="Int NOT NULL")]
		public int ClaimStatusType_ID
		{
			get
			{
				return this._ClaimStatusType_ID;
			}
			set
			{
				if ((this._ClaimStatusType_ID != value))
				{
					this.OnClaimStatusType_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimStatusType_ID = value;
					this.SendPropertyChanged("ClaimStatusType_ID");
					this.OnClaimStatusType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchNumber_VC", DbType="VarChar(14)")]
		public string BatchNumber_VC
		{
			get
			{
				return this._BatchNumber_VC;
			}
			set
			{
				if ((this._BatchNumber_VC != value))
				{
					this.OnBatchNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._BatchNumber_VC = value;
					this.SendPropertyChanged("BatchNumber_VC");
					this.OnBatchNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportDate_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReportDate_DT
		{
			get
			{
				return this._ReportDate_DT;
			}
			set
			{
				if ((this._ReportDate_DT != value))
				{
					this.OnReportDate_DTChanging(value);
					this.SendPropertyChanging();
					this._ReportDate_DT = value;
					this.SendPropertyChanged("ReportDate_DT");
					this.OnReportDate_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPI_VC", DbType="VarChar(10)")]
		public string NPI_VC
		{
			get
			{
				return this._NPI_VC;
			}
			set
			{
				if ((this._NPI_VC != value))
				{
					this.OnNPI_VCChanging(value);
					this.SendPropertyChanging();
					this._NPI_VC = value;
					this.SendPropertyChanged("NPI_VC");
					this.OnNPI_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastProcessDate_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastProcessDate_DT
		{
			get
			{
				return this._LastProcessDate_DT;
			}
			set
			{
				if ((this._LastProcessDate_DT != value))
				{
					this.OnLastProcessDate_DTChanging(value);
					this.SendPropertyChanging();
					this._LastProcessDate_DT = value;
					this.SendPropertyChanged("LastProcessDate_DT");
					this.OnLastProcessDate_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID_VC", DbType="VarChar(3)")]
		public string ClientID_VC
		{
			get
			{
				return this._ClientID_VC;
			}
			set
			{
				if ((this._ClientID_VC != value))
				{
					this.OnClientID_VCChanging(value);
					this.SendPropertyChanging();
					this._ClientID_VC = value;
					this.SendPropertyChanged("ClientID_VC");
					this.OnClientID_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyClaim_ID", DbType="BigInt")]
		public System.Nullable<long> LegacyClaim_ID
		{
			get
			{
				return this._LegacyClaim_ID;
			}
			set
			{
				if ((this._LegacyClaim_ID != value))
				{
					this.OnLegacyClaim_IDChanging(value);
					this.SendPropertyChanging();
					this._LegacyClaim_ID = value;
					this.SendPropertyChanged("LegacyClaim_ID");
					this.OnLegacyClaim_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateDate_DT", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdateDate_DT
		{
			get
			{
				return this._LastUpdateDate_DT;
			}
			set
			{
				if ((this._LastUpdateDate_DT != value))
				{
					this.OnLastUpdateDate_DTChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateDate_DT = value;
					this.SendPropertyChanged("LastUpdateDate_DT");
					this.OnLastUpdateDate_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNoCharge_BT", DbType="Bit NOT NULL")]
		public bool IsNoCharge_BT
		{
			get
			{
				return this._IsNoCharge_BT;
			}
			set
			{
				if ((this._IsNoCharge_BT != value))
				{
					this.OnIsNoCharge_BTChanging(value);
					this.SendPropertyChanging();
					this._IsNoCharge_BT = value;
					this.SendPropertyChanged("IsNoCharge_BT");
					this.OnIsNoCharge_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProcessNow_BT", DbType="Bit NOT NULL")]
		public bool IsProcessNow_BT
		{
			get
			{
				return this._IsProcessNow_BT;
			}
			set
			{
				if ((this._IsProcessNow_BT != value))
				{
					this.OnIsProcessNow_BTChanging(value);
					this.SendPropertyChanging();
					this._IsProcessNow_BT = value;
					this.SendPropertyChanged("IsProcessNow_BT");
					this.OnIsProcessNow_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalNotes_VC", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string InternalNotes_VC
		{
			get
			{
				return this._InternalNotes_VC;
			}
			set
			{
				if ((this._InternalNotes_VC != value))
				{
					this.OnInternalNotes_VCChanging(value);
					this.SendPropertyChanging();
					this._InternalNotes_VC = value;
					this.SendPropertyChanged("InternalNotes_VC");
					this.OnInternalNotes_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApexPayerID_VC", DbType="VarChar(5)")]
		public string ApexPayerID_VC
		{
			get
			{
				return this._ApexPayerID_VC;
			}
			set
			{
				if ((this._ApexPayerID_VC != value))
				{
					this.OnApexPayerID_VCChanging(value);
					this.SendPropertyChanging();
					this._ApexPayerID_VC = value;
					this.SendPropertyChanged("ApexPayerID_VC");
					this.OnApexPayerID_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimVendorID_VC", DbType="VarChar(20)")]
		public string ClaimVendorID_VC
		{
			get
			{
				return this._ClaimVendorID_VC;
			}
			set
			{
				if ((this._ClaimVendorID_VC != value))
				{
					this.OnClaimVendorID_VCChanging(value);
					this.SendPropertyChanging();
					this._ClaimVendorID_VC = value;
					this.SendPropertyChanged("ClaimVendorID_VC");
					this.OnClaimVendorID_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventPhase_ID", DbType="Int")]
		public System.Nullable<int> EventPhase_ID
		{
			get
			{
				return this._EventPhase_ID;
			}
			set
			{
				if ((this._EventPhase_ID != value))
				{
					this.OnEventPhase_IDChanging(value);
					this.SendPropertyChanging();
					this._EventPhase_ID = value;
					this.SendPropertyChanged("EventPhase_ID");
					this.OnEventPhase_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventType_ID", DbType="BigInt")]
		public System.Nullable<long> EventType_ID
		{
			get
			{
				return this._EventType_ID;
			}
			set
			{
				if ((this._EventType_ID != value))
				{
					this.OnEventType_IDChanging(value);
					this.SendPropertyChanging();
					this._EventType_ID = value;
					this.SendPropertyChanged("EventType_ID");
					this.OnEventType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor_ID", DbType="Int")]
		public System.Nullable<int> Vendor_ID
		{
			get
			{
				return this._Vendor_ID;
			}
			set
			{
				if ((this._Vendor_ID != value))
				{
					this.OnVendor_IDChanging(value);
					this.SendPropertyChanging();
					this._Vendor_ID = value;
					this.SendPropertyChanged("Vendor_ID");
					this.OnVendor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClaimMedicalBase_T_ClaimMedicalClaimInformation_T", Storage="_ClaimMedicalClaimInformation_Ts", ThisKey="ClaimMedicalBase_ID", OtherKey="ClaimMedicalBase_ID")]
		public EntitySet<ClaimMedicalClaimInformation_T> ClaimMedicalClaimInformation_Ts
		{
			get
			{
				return this._ClaimMedicalClaimInformation_Ts;
			}
			set
			{
				this._ClaimMedicalClaimInformation_Ts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ClaimMedicalClaimInformation_Ts(ClaimMedicalClaimInformation_T entity)
		{
			this.SendPropertyChanging();
			entity.ClaimMedicalBase_T = this;
		}
		
		private void detach_ClaimMedicalClaimInformation_Ts(ClaimMedicalClaimInformation_T entity)
		{
			this.SendPropertyChanging();
			entity.ClaimMedicalBase_T = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClaimMedicalClaimInformation_T")]
	public partial class ClaimMedicalClaimInformation_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ClaimMedicalClaimInformation_ID;
		
		private long _ClaimMedicalBase_ID;
		
		private System.Nullable<int> _NoteReferenceCode_ID;
		
		private System.Nullable<byte> _DisabilityDateTimeQualifier_ID;
		
		private System.Nullable<byte> _DisabilityDateTimePeriodFormatQualifier_ID;
		
		private System.Nullable<int> _ClaimMedicalPricingRepricingInformation_ID;
		
		private System.Nullable<int> _ClaimMedicalAmbulanceTransportInformation_ID;
		
		private System.Nullable<int> _ClaimMedicalAmbulancePickup_ID;
		
		private System.Nullable<int> _ClaimMedicalAmbulanceDropoff_ID;
		
		private string _ProviderOrSupplierSignatureIndicator_VC;
		
		private string _AssignmentOrPlanParticipationCode_VC;
		
		private string _BenefitsAssignmentCertificationIndicator_VC;
		
		private string _ReleaseOfInformationCode_VC;
		
		private string _DelayReasonCode_VC;
		
		private string _PatientAccountNumber_VC;
		
		private string _TotalClaimChargeAmount_VC;
		
		private string _PlaceOfServiceCode_VC;
		
		private string _ClaimFrequencyCode_VC;
		
		private string _RelatedCausesCode1_VC;
		
		private string _RelatedCausesCode2_VC;
		
		private string _AutoAccidentStateOrProvinceCode_VC;
		
		private string _AutoAccidentCountryCode_VC;
		
		private string _SpecialProgramCode_VC;
		
		private string _DateOfService_VC;
		
		private string _DateOnsetOfCurrentIllnessOrInjury_VC;
		
		private string _DateInitialTreatment_VC;
		
		private string _DateLastSeen_VC;
		
		private string _DateAcuteManifestation_VC;
		
		private string _DateAccident_VC;
		
		private string _DateLastMenstrualPeriod_VC;
		
		private string _DateLastXRay_VC;
		
		private string _DatePrescription_VC;
		
		private string _DateDisabilityFrom_VC;
		
		private string _DateDisabilityTo_VC;
		
		private string _DateLastWorked_VC;
		
		private string _DateWorkReturn_VC;
		
		private string _DateRelatedHospitalizationAdmission_VC;
		
		private string _DateRelatedHospitalizationDischarge_VC;
		
		private string _DateAssumedOrRelinquishedCareStart_VC;
		
		private string _DateAssumedOrRelinquishedCareEnd_VC;
		
		private string _DatePropertyAndCasualtyDateOfFirstContact_VC;
		
		private string _DateRepricerReceived_VC;
		
		private string _ContractTypeCode_VC;
		
		private string _ContractAmount_VC;
		
		private string _ContractPercentage_VC;
		
		private string _ContractCode_VC;
		
		private string _TermsDiscountPercentage_VC;
		
		private string _ContractVersionIdentifier_VC;
		
		private string _PatientAmountPaid_VC;
		
		private string _NoteText_VC;
		
		private bool _HomeboundIndicator_BT;
		
		private bool _OutputPatientSignatureSourceCode_BT;
		
		private string _PatientConditionCode_VC;
		
		private string _SpinalManipulationPatientConditionCode_VC;
		
		private string _SpinalManipulationPatientConditionDescription1_VC;
		
		private string _SpinalManipulationPatientConditionDescription2_VC;
		
		private string _EPSDTReferralCertificationConditionCodeAppliesIndicator_VC;
		
		private string _EPSDTReferralConditionIndicator1_VC;
		
		private string _EPSDTReferralConditionIndicator2_VC;
		
		private string _EPSDTReferralConditionIndicator3_VC;
		
		private string _AnesthesiaRelatedSurgicalProcedure_VC;
		
		private string _AnesthesiaRelatedSurgicalProcedure2_VC;
		
		private string _ServiceAuthorizationExceptionCode_VC;
		
		private string _MedicareSection4081Indicator_VC;
		
		private string _MammographyCertificationNumber_VC;
		
		private string _ReferralNumber_VC;
		
		private string _PriorAuthorization_VC;
		
		private string _PayerClaimControlNumber_VC;
		
		private string _ClinicalLaboratoryImprovementAmendmentNumber_VC;
		
		private string _RepricedClaimReferenceNumber_VC;
		
		private string _AdjustedRepricedClaimReferenceNumber_VC;
		
		private string _InvestigationalDeviceExemptionNumber_VC;
		
		private string _ValueAddedNetworkTraceNumber_VC;
		
		private string _MedicalRecordNumber_VC;
		
		private string _DemonstrationProjectIdentifier_VC;
		
		private string _CarePlanOversightNumber_VC;
		
		private string _ReservedForLocal19_VC;
		
		private EntityRef<ClaimMedicalBase_T> _ClaimMedicalBase_T;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClaimMedicalClaimInformation_IDChanging(long value);
    partial void OnClaimMedicalClaimInformation_IDChanged();
    partial void OnClaimMedicalBase_IDChanging(long value);
    partial void OnClaimMedicalBase_IDChanged();
    partial void OnNoteReferenceCode_IDChanging(System.Nullable<int> value);
    partial void OnNoteReferenceCode_IDChanged();
    partial void OnDisabilityDateTimeQualifier_IDChanging(System.Nullable<byte> value);
    partial void OnDisabilityDateTimeQualifier_IDChanged();
    partial void OnDisabilityDateTimePeriodFormatQualifier_IDChanging(System.Nullable<byte> value);
    partial void OnDisabilityDateTimePeriodFormatQualifier_IDChanged();
    partial void OnClaimMedicalPricingRepricingInformation_IDChanging(System.Nullable<int> value);
    partial void OnClaimMedicalPricingRepricingInformation_IDChanged();
    partial void OnClaimMedicalAmbulanceTransportInformation_IDChanging(System.Nullable<int> value);
    partial void OnClaimMedicalAmbulanceTransportInformation_IDChanged();
    partial void OnClaimMedicalAmbulancePickup_IDChanging(System.Nullable<int> value);
    partial void OnClaimMedicalAmbulancePickup_IDChanged();
    partial void OnClaimMedicalAmbulanceDropoff_IDChanging(System.Nullable<int> value);
    partial void OnClaimMedicalAmbulanceDropoff_IDChanged();
    partial void OnProviderOrSupplierSignatureIndicator_VCChanging(string value);
    partial void OnProviderOrSupplierSignatureIndicator_VCChanged();
    partial void OnAssignmentOrPlanParticipationCode_VCChanging(string value);
    partial void OnAssignmentOrPlanParticipationCode_VCChanged();
    partial void OnBenefitsAssignmentCertificationIndicator_VCChanging(string value);
    partial void OnBenefitsAssignmentCertificationIndicator_VCChanged();
    partial void OnReleaseOfInformationCode_VCChanging(string value);
    partial void OnReleaseOfInformationCode_VCChanged();
    partial void OnDelayReasonCode_VCChanging(string value);
    partial void OnDelayReasonCode_VCChanged();
    partial void OnPatientAccountNumber_VCChanging(string value);
    partial void OnPatientAccountNumber_VCChanged();
    partial void OnTotalClaimChargeAmount_VCChanging(string value);
    partial void OnTotalClaimChargeAmount_VCChanged();
    partial void OnPlaceOfServiceCode_VCChanging(string value);
    partial void OnPlaceOfServiceCode_VCChanged();
    partial void OnClaimFrequencyCode_VCChanging(string value);
    partial void OnClaimFrequencyCode_VCChanged();
    partial void OnRelatedCausesCode1_VCChanging(string value);
    partial void OnRelatedCausesCode1_VCChanged();
    partial void OnRelatedCausesCode2_VCChanging(string value);
    partial void OnRelatedCausesCode2_VCChanged();
    partial void OnAutoAccidentStateOrProvinceCode_VCChanging(string value);
    partial void OnAutoAccidentStateOrProvinceCode_VCChanged();
    partial void OnAutoAccidentCountryCode_VCChanging(string value);
    partial void OnAutoAccidentCountryCode_VCChanged();
    partial void OnSpecialProgramCode_VCChanging(string value);
    partial void OnSpecialProgramCode_VCChanged();
    partial void OnDateOfService_VCChanging(string value);
    partial void OnDateOfService_VCChanged();
    partial void OnDateOnsetOfCurrentIllnessOrInjury_VCChanging(string value);
    partial void OnDateOnsetOfCurrentIllnessOrInjury_VCChanged();
    partial void OnDateInitialTreatment_VCChanging(string value);
    partial void OnDateInitialTreatment_VCChanged();
    partial void OnDateLastSeen_VCChanging(string value);
    partial void OnDateLastSeen_VCChanged();
    partial void OnDateAcuteManifestation_VCChanging(string value);
    partial void OnDateAcuteManifestation_VCChanged();
    partial void OnDateAccident_VCChanging(string value);
    partial void OnDateAccident_VCChanged();
    partial void OnDateLastMenstrualPeriod_VCChanging(string value);
    partial void OnDateLastMenstrualPeriod_VCChanged();
    partial void OnDateLastXRay_VCChanging(string value);
    partial void OnDateLastXRay_VCChanged();
    partial void OnDatePrescription_VCChanging(string value);
    partial void OnDatePrescription_VCChanged();
    partial void OnDateDisabilityFrom_VCChanging(string value);
    partial void OnDateDisabilityFrom_VCChanged();
    partial void OnDateDisabilityTo_VCChanging(string value);
    partial void OnDateDisabilityTo_VCChanged();
    partial void OnDateLastWorked_VCChanging(string value);
    partial void OnDateLastWorked_VCChanged();
    partial void OnDateWorkReturn_VCChanging(string value);
    partial void OnDateWorkReturn_VCChanged();
    partial void OnDateRelatedHospitalizationAdmission_VCChanging(string value);
    partial void OnDateRelatedHospitalizationAdmission_VCChanged();
    partial void OnDateRelatedHospitalizationDischarge_VCChanging(string value);
    partial void OnDateRelatedHospitalizationDischarge_VCChanged();
    partial void OnDateAssumedOrRelinquishedCareStart_VCChanging(string value);
    partial void OnDateAssumedOrRelinquishedCareStart_VCChanged();
    partial void OnDateAssumedOrRelinquishedCareEnd_VCChanging(string value);
    partial void OnDateAssumedOrRelinquishedCareEnd_VCChanged();
    partial void OnDatePropertyAndCasualtyDateOfFirstContact_VCChanging(string value);
    partial void OnDatePropertyAndCasualtyDateOfFirstContact_VCChanged();
    partial void OnDateRepricerReceived_VCChanging(string value);
    partial void OnDateRepricerReceived_VCChanged();
    partial void OnContractTypeCode_VCChanging(string value);
    partial void OnContractTypeCode_VCChanged();
    partial void OnContractAmount_VCChanging(string value);
    partial void OnContractAmount_VCChanged();
    partial void OnContractPercentage_VCChanging(string value);
    partial void OnContractPercentage_VCChanged();
    partial void OnContractCode_VCChanging(string value);
    partial void OnContractCode_VCChanged();
    partial void OnTermsDiscountPercentage_VCChanging(string value);
    partial void OnTermsDiscountPercentage_VCChanged();
    partial void OnContractVersionIdentifier_VCChanging(string value);
    partial void OnContractVersionIdentifier_VCChanged();
    partial void OnPatientAmountPaid_VCChanging(string value);
    partial void OnPatientAmountPaid_VCChanged();
    partial void OnNoteText_VCChanging(string value);
    partial void OnNoteText_VCChanged();
    partial void OnHomeboundIndicator_BTChanging(bool value);
    partial void OnHomeboundIndicator_BTChanged();
    partial void OnOutputPatientSignatureSourceCode_BTChanging(bool value);
    partial void OnOutputPatientSignatureSourceCode_BTChanged();
    partial void OnPatientConditionCode_VCChanging(string value);
    partial void OnPatientConditionCode_VCChanged();
    partial void OnSpinalManipulationPatientConditionCode_VCChanging(string value);
    partial void OnSpinalManipulationPatientConditionCode_VCChanged();
    partial void OnSpinalManipulationPatientConditionDescription1_VCChanging(string value);
    partial void OnSpinalManipulationPatientConditionDescription1_VCChanged();
    partial void OnSpinalManipulationPatientConditionDescription2_VCChanging(string value);
    partial void OnSpinalManipulationPatientConditionDescription2_VCChanged();
    partial void OnEPSDTReferralCertificationConditionCodeAppliesIndicator_VCChanging(string value);
    partial void OnEPSDTReferralCertificationConditionCodeAppliesIndicator_VCChanged();
    partial void OnEPSDTReferralConditionIndicator1_VCChanging(string value);
    partial void OnEPSDTReferralConditionIndicator1_VCChanged();
    partial void OnEPSDTReferralConditionIndicator2_VCChanging(string value);
    partial void OnEPSDTReferralConditionIndicator2_VCChanged();
    partial void OnEPSDTReferralConditionIndicator3_VCChanging(string value);
    partial void OnEPSDTReferralConditionIndicator3_VCChanged();
    partial void OnAnesthesiaRelatedSurgicalProcedure_VCChanging(string value);
    partial void OnAnesthesiaRelatedSurgicalProcedure_VCChanged();
    partial void OnAnesthesiaRelatedSurgicalProcedure2_VCChanging(string value);
    partial void OnAnesthesiaRelatedSurgicalProcedure2_VCChanged();
    partial void OnServiceAuthorizationExceptionCode_VCChanging(string value);
    partial void OnServiceAuthorizationExceptionCode_VCChanged();
    partial void OnMedicareSection4081Indicator_VCChanging(string value);
    partial void OnMedicareSection4081Indicator_VCChanged();
    partial void OnMammographyCertificationNumber_VCChanging(string value);
    partial void OnMammographyCertificationNumber_VCChanged();
    partial void OnReferralNumber_VCChanging(string value);
    partial void OnReferralNumber_VCChanged();
    partial void OnPriorAuthorization_VCChanging(string value);
    partial void OnPriorAuthorization_VCChanged();
    partial void OnPayerClaimControlNumber_VCChanging(string value);
    partial void OnPayerClaimControlNumber_VCChanged();
    partial void OnClinicalLaboratoryImprovementAmendmentNumber_VCChanging(string value);
    partial void OnClinicalLaboratoryImprovementAmendmentNumber_VCChanged();
    partial void OnRepricedClaimReferenceNumber_VCChanging(string value);
    partial void OnRepricedClaimReferenceNumber_VCChanged();
    partial void OnAdjustedRepricedClaimReferenceNumber_VCChanging(string value);
    partial void OnAdjustedRepricedClaimReferenceNumber_VCChanged();
    partial void OnInvestigationalDeviceExemptionNumber_VCChanging(string value);
    partial void OnInvestigationalDeviceExemptionNumber_VCChanged();
    partial void OnValueAddedNetworkTraceNumber_VCChanging(string value);
    partial void OnValueAddedNetworkTraceNumber_VCChanged();
    partial void OnMedicalRecordNumber_VCChanging(string value);
    partial void OnMedicalRecordNumber_VCChanged();
    partial void OnDemonstrationProjectIdentifier_VCChanging(string value);
    partial void OnDemonstrationProjectIdentifier_VCChanged();
    partial void OnCarePlanOversightNumber_VCChanging(string value);
    partial void OnCarePlanOversightNumber_VCChanged();
    partial void OnReservedForLocal19_VCChanging(string value);
    partial void OnReservedForLocal19_VCChanged();
    #endregion
		
		public ClaimMedicalClaimInformation_T()
		{
			this._ClaimMedicalBase_T = default(EntityRef<ClaimMedicalBase_T>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalClaimInformation_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ClaimMedicalClaimInformation_ID
		{
			get
			{
				return this._ClaimMedicalClaimInformation_ID;
			}
			set
			{
				if ((this._ClaimMedicalClaimInformation_ID != value))
				{
					this.OnClaimMedicalClaimInformation_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalClaimInformation_ID = value;
					this.SendPropertyChanged("ClaimMedicalClaimInformation_ID");
					this.OnClaimMedicalClaimInformation_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalBase_ID", DbType="BigInt NOT NULL")]
		public long ClaimMedicalBase_ID
		{
			get
			{
				return this._ClaimMedicalBase_ID;
			}
			set
			{
				if ((this._ClaimMedicalBase_ID != value))
				{
					if (this._ClaimMedicalBase_T.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClaimMedicalBase_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalBase_ID = value;
					this.SendPropertyChanged("ClaimMedicalBase_ID");
					this.OnClaimMedicalBase_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteReferenceCode_ID", DbType="Int")]
		public System.Nullable<int> NoteReferenceCode_ID
		{
			get
			{
				return this._NoteReferenceCode_ID;
			}
			set
			{
				if ((this._NoteReferenceCode_ID != value))
				{
					this.OnNoteReferenceCode_IDChanging(value);
					this.SendPropertyChanging();
					this._NoteReferenceCode_ID = value;
					this.SendPropertyChanged("NoteReferenceCode_ID");
					this.OnNoteReferenceCode_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisabilityDateTimeQualifier_ID", DbType="TinyInt")]
		public System.Nullable<byte> DisabilityDateTimeQualifier_ID
		{
			get
			{
				return this._DisabilityDateTimeQualifier_ID;
			}
			set
			{
				if ((this._DisabilityDateTimeQualifier_ID != value))
				{
					this.OnDisabilityDateTimeQualifier_IDChanging(value);
					this.SendPropertyChanging();
					this._DisabilityDateTimeQualifier_ID = value;
					this.SendPropertyChanged("DisabilityDateTimeQualifier_ID");
					this.OnDisabilityDateTimeQualifier_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisabilityDateTimePeriodFormatQualifier_ID", DbType="TinyInt")]
		public System.Nullable<byte> DisabilityDateTimePeriodFormatQualifier_ID
		{
			get
			{
				return this._DisabilityDateTimePeriodFormatQualifier_ID;
			}
			set
			{
				if ((this._DisabilityDateTimePeriodFormatQualifier_ID != value))
				{
					this.OnDisabilityDateTimePeriodFormatQualifier_IDChanging(value);
					this.SendPropertyChanging();
					this._DisabilityDateTimePeriodFormatQualifier_ID = value;
					this.SendPropertyChanged("DisabilityDateTimePeriodFormatQualifier_ID");
					this.OnDisabilityDateTimePeriodFormatQualifier_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalPricingRepricingInformation_ID", DbType="Int")]
		public System.Nullable<int> ClaimMedicalPricingRepricingInformation_ID
		{
			get
			{
				return this._ClaimMedicalPricingRepricingInformation_ID;
			}
			set
			{
				if ((this._ClaimMedicalPricingRepricingInformation_ID != value))
				{
					this.OnClaimMedicalPricingRepricingInformation_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalPricingRepricingInformation_ID = value;
					this.SendPropertyChanged("ClaimMedicalPricingRepricingInformation_ID");
					this.OnClaimMedicalPricingRepricingInformation_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalAmbulanceTransportInformation_ID", DbType="Int")]
		public System.Nullable<int> ClaimMedicalAmbulanceTransportInformation_ID
		{
			get
			{
				return this._ClaimMedicalAmbulanceTransportInformation_ID;
			}
			set
			{
				if ((this._ClaimMedicalAmbulanceTransportInformation_ID != value))
				{
					this.OnClaimMedicalAmbulanceTransportInformation_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalAmbulanceTransportInformation_ID = value;
					this.SendPropertyChanged("ClaimMedicalAmbulanceTransportInformation_ID");
					this.OnClaimMedicalAmbulanceTransportInformation_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalAmbulancePickup_ID", DbType="Int")]
		public System.Nullable<int> ClaimMedicalAmbulancePickup_ID
		{
			get
			{
				return this._ClaimMedicalAmbulancePickup_ID;
			}
			set
			{
				if ((this._ClaimMedicalAmbulancePickup_ID != value))
				{
					this.OnClaimMedicalAmbulancePickup_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalAmbulancePickup_ID = value;
					this.SendPropertyChanged("ClaimMedicalAmbulancePickup_ID");
					this.OnClaimMedicalAmbulancePickup_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimMedicalAmbulanceDropoff_ID", DbType="Int")]
		public System.Nullable<int> ClaimMedicalAmbulanceDropoff_ID
		{
			get
			{
				return this._ClaimMedicalAmbulanceDropoff_ID;
			}
			set
			{
				if ((this._ClaimMedicalAmbulanceDropoff_ID != value))
				{
					this.OnClaimMedicalAmbulanceDropoff_IDChanging(value);
					this.SendPropertyChanging();
					this._ClaimMedicalAmbulanceDropoff_ID = value;
					this.SendPropertyChanged("ClaimMedicalAmbulanceDropoff_ID");
					this.OnClaimMedicalAmbulanceDropoff_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderOrSupplierSignatureIndicator_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ProviderOrSupplierSignatureIndicator_VC
		{
			get
			{
				return this._ProviderOrSupplierSignatureIndicator_VC;
			}
			set
			{
				if ((this._ProviderOrSupplierSignatureIndicator_VC != value))
				{
					this.OnProviderOrSupplierSignatureIndicator_VCChanging(value);
					this.SendPropertyChanging();
					this._ProviderOrSupplierSignatureIndicator_VC = value;
					this.SendPropertyChanged("ProviderOrSupplierSignatureIndicator_VC");
					this.OnProviderOrSupplierSignatureIndicator_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignmentOrPlanParticipationCode_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string AssignmentOrPlanParticipationCode_VC
		{
			get
			{
				return this._AssignmentOrPlanParticipationCode_VC;
			}
			set
			{
				if ((this._AssignmentOrPlanParticipationCode_VC != value))
				{
					this.OnAssignmentOrPlanParticipationCode_VCChanging(value);
					this.SendPropertyChanging();
					this._AssignmentOrPlanParticipationCode_VC = value;
					this.SendPropertyChanged("AssignmentOrPlanParticipationCode_VC");
					this.OnAssignmentOrPlanParticipationCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BenefitsAssignmentCertificationIndicator_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BenefitsAssignmentCertificationIndicator_VC
		{
			get
			{
				return this._BenefitsAssignmentCertificationIndicator_VC;
			}
			set
			{
				if ((this._BenefitsAssignmentCertificationIndicator_VC != value))
				{
					this.OnBenefitsAssignmentCertificationIndicator_VCChanging(value);
					this.SendPropertyChanging();
					this._BenefitsAssignmentCertificationIndicator_VC = value;
					this.SendPropertyChanged("BenefitsAssignmentCertificationIndicator_VC");
					this.OnBenefitsAssignmentCertificationIndicator_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseOfInformationCode_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ReleaseOfInformationCode_VC
		{
			get
			{
				return this._ReleaseOfInformationCode_VC;
			}
			set
			{
				if ((this._ReleaseOfInformationCode_VC != value))
				{
					this.OnReleaseOfInformationCode_VCChanging(value);
					this.SendPropertyChanging();
					this._ReleaseOfInformationCode_VC = value;
					this.SendPropertyChanged("ReleaseOfInformationCode_VC");
					this.OnReleaseOfInformationCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelayReasonCode_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string DelayReasonCode_VC
		{
			get
			{
				return this._DelayReasonCode_VC;
			}
			set
			{
				if ((this._DelayReasonCode_VC != value))
				{
					this.OnDelayReasonCode_VCChanging(value);
					this.SendPropertyChanging();
					this._DelayReasonCode_VC = value;
					this.SendPropertyChanged("DelayReasonCode_VC");
					this.OnDelayReasonCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAccountNumber_VC", DbType="VarChar(38) NOT NULL", CanBeNull=false)]
		public string PatientAccountNumber_VC
		{
			get
			{
				return this._PatientAccountNumber_VC;
			}
			set
			{
				if ((this._PatientAccountNumber_VC != value))
				{
					this.OnPatientAccountNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._PatientAccountNumber_VC = value;
					this.SendPropertyChanged("PatientAccountNumber_VC");
					this.OnPatientAccountNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalClaimChargeAmount_VC", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string TotalClaimChargeAmount_VC
		{
			get
			{
				return this._TotalClaimChargeAmount_VC;
			}
			set
			{
				if ((this._TotalClaimChargeAmount_VC != value))
				{
					this.OnTotalClaimChargeAmount_VCChanging(value);
					this.SendPropertyChanging();
					this._TotalClaimChargeAmount_VC = value;
					this.SendPropertyChanged("TotalClaimChargeAmount_VC");
					this.OnTotalClaimChargeAmount_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceOfServiceCode_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string PlaceOfServiceCode_VC
		{
			get
			{
				return this._PlaceOfServiceCode_VC;
			}
			set
			{
				if ((this._PlaceOfServiceCode_VC != value))
				{
					this.OnPlaceOfServiceCode_VCChanging(value);
					this.SendPropertyChanging();
					this._PlaceOfServiceCode_VC = value;
					this.SendPropertyChanged("PlaceOfServiceCode_VC");
					this.OnPlaceOfServiceCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimFrequencyCode_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ClaimFrequencyCode_VC
		{
			get
			{
				return this._ClaimFrequencyCode_VC;
			}
			set
			{
				if ((this._ClaimFrequencyCode_VC != value))
				{
					this.OnClaimFrequencyCode_VCChanging(value);
					this.SendPropertyChanging();
					this._ClaimFrequencyCode_VC = value;
					this.SendPropertyChanged("ClaimFrequencyCode_VC");
					this.OnClaimFrequencyCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedCausesCode1_VC", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string RelatedCausesCode1_VC
		{
			get
			{
				return this._RelatedCausesCode1_VC;
			}
			set
			{
				if ((this._RelatedCausesCode1_VC != value))
				{
					this.OnRelatedCausesCode1_VCChanging(value);
					this.SendPropertyChanging();
					this._RelatedCausesCode1_VC = value;
					this.SendPropertyChanged("RelatedCausesCode1_VC");
					this.OnRelatedCausesCode1_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedCausesCode2_VC", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string RelatedCausesCode2_VC
		{
			get
			{
				return this._RelatedCausesCode2_VC;
			}
			set
			{
				if ((this._RelatedCausesCode2_VC != value))
				{
					this.OnRelatedCausesCode2_VCChanging(value);
					this.SendPropertyChanging();
					this._RelatedCausesCode2_VC = value;
					this.SendPropertyChanged("RelatedCausesCode2_VC");
					this.OnRelatedCausesCode2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoAccidentStateOrProvinceCode_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string AutoAccidentStateOrProvinceCode_VC
		{
			get
			{
				return this._AutoAccidentStateOrProvinceCode_VC;
			}
			set
			{
				if ((this._AutoAccidentStateOrProvinceCode_VC != value))
				{
					this.OnAutoAccidentStateOrProvinceCode_VCChanging(value);
					this.SendPropertyChanging();
					this._AutoAccidentStateOrProvinceCode_VC = value;
					this.SendPropertyChanged("AutoAccidentStateOrProvinceCode_VC");
					this.OnAutoAccidentStateOrProvinceCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoAccidentCountryCode_VC", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string AutoAccidentCountryCode_VC
		{
			get
			{
				return this._AutoAccidentCountryCode_VC;
			}
			set
			{
				if ((this._AutoAccidentCountryCode_VC != value))
				{
					this.OnAutoAccidentCountryCode_VCChanging(value);
					this.SendPropertyChanging();
					this._AutoAccidentCountryCode_VC = value;
					this.SendPropertyChanged("AutoAccidentCountryCode_VC");
					this.OnAutoAccidentCountryCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialProgramCode_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string SpecialProgramCode_VC
		{
			get
			{
				return this._SpecialProgramCode_VC;
			}
			set
			{
				if ((this._SpecialProgramCode_VC != value))
				{
					this.OnSpecialProgramCode_VCChanging(value);
					this.SendPropertyChanging();
					this._SpecialProgramCode_VC = value;
					this.SendPropertyChanged("SpecialProgramCode_VC");
					this.OnSpecialProgramCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfService_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateOfService_VC
		{
			get
			{
				return this._DateOfService_VC;
			}
			set
			{
				if ((this._DateOfService_VC != value))
				{
					this.OnDateOfService_VCChanging(value);
					this.SendPropertyChanging();
					this._DateOfService_VC = value;
					this.SendPropertyChanged("DateOfService_VC");
					this.OnDateOfService_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOnsetOfCurrentIllnessOrInjury_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateOnsetOfCurrentIllnessOrInjury_VC
		{
			get
			{
				return this._DateOnsetOfCurrentIllnessOrInjury_VC;
			}
			set
			{
				if ((this._DateOnsetOfCurrentIllnessOrInjury_VC != value))
				{
					this.OnDateOnsetOfCurrentIllnessOrInjury_VCChanging(value);
					this.SendPropertyChanging();
					this._DateOnsetOfCurrentIllnessOrInjury_VC = value;
					this.SendPropertyChanged("DateOnsetOfCurrentIllnessOrInjury_VC");
					this.OnDateOnsetOfCurrentIllnessOrInjury_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInitialTreatment_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateInitialTreatment_VC
		{
			get
			{
				return this._DateInitialTreatment_VC;
			}
			set
			{
				if ((this._DateInitialTreatment_VC != value))
				{
					this.OnDateInitialTreatment_VCChanging(value);
					this.SendPropertyChanging();
					this._DateInitialTreatment_VC = value;
					this.SendPropertyChanged("DateInitialTreatment_VC");
					this.OnDateInitialTreatment_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastSeen_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateLastSeen_VC
		{
			get
			{
				return this._DateLastSeen_VC;
			}
			set
			{
				if ((this._DateLastSeen_VC != value))
				{
					this.OnDateLastSeen_VCChanging(value);
					this.SendPropertyChanging();
					this._DateLastSeen_VC = value;
					this.SendPropertyChanged("DateLastSeen_VC");
					this.OnDateLastSeen_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAcuteManifestation_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateAcuteManifestation_VC
		{
			get
			{
				return this._DateAcuteManifestation_VC;
			}
			set
			{
				if ((this._DateAcuteManifestation_VC != value))
				{
					this.OnDateAcuteManifestation_VCChanging(value);
					this.SendPropertyChanging();
					this._DateAcuteManifestation_VC = value;
					this.SendPropertyChanged("DateAcuteManifestation_VC");
					this.OnDateAcuteManifestation_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAccident_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateAccident_VC
		{
			get
			{
				return this._DateAccident_VC;
			}
			set
			{
				if ((this._DateAccident_VC != value))
				{
					this.OnDateAccident_VCChanging(value);
					this.SendPropertyChanging();
					this._DateAccident_VC = value;
					this.SendPropertyChanged("DateAccident_VC");
					this.OnDateAccident_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastMenstrualPeriod_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateLastMenstrualPeriod_VC
		{
			get
			{
				return this._DateLastMenstrualPeriod_VC;
			}
			set
			{
				if ((this._DateLastMenstrualPeriod_VC != value))
				{
					this.OnDateLastMenstrualPeriod_VCChanging(value);
					this.SendPropertyChanging();
					this._DateLastMenstrualPeriod_VC = value;
					this.SendPropertyChanged("DateLastMenstrualPeriod_VC");
					this.OnDateLastMenstrualPeriod_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastXRay_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateLastXRay_VC
		{
			get
			{
				return this._DateLastXRay_VC;
			}
			set
			{
				if ((this._DateLastXRay_VC != value))
				{
					this.OnDateLastXRay_VCChanging(value);
					this.SendPropertyChanging();
					this._DateLastXRay_VC = value;
					this.SendPropertyChanged("DateLastXRay_VC");
					this.OnDateLastXRay_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePrescription_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DatePrescription_VC
		{
			get
			{
				return this._DatePrescription_VC;
			}
			set
			{
				if ((this._DatePrescription_VC != value))
				{
					this.OnDatePrescription_VCChanging(value);
					this.SendPropertyChanging();
					this._DatePrescription_VC = value;
					this.SendPropertyChanged("DatePrescription_VC");
					this.OnDatePrescription_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDisabilityFrom_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateDisabilityFrom_VC
		{
			get
			{
				return this._DateDisabilityFrom_VC;
			}
			set
			{
				if ((this._DateDisabilityFrom_VC != value))
				{
					this.OnDateDisabilityFrom_VCChanging(value);
					this.SendPropertyChanging();
					this._DateDisabilityFrom_VC = value;
					this.SendPropertyChanged("DateDisabilityFrom_VC");
					this.OnDateDisabilityFrom_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDisabilityTo_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateDisabilityTo_VC
		{
			get
			{
				return this._DateDisabilityTo_VC;
			}
			set
			{
				if ((this._DateDisabilityTo_VC != value))
				{
					this.OnDateDisabilityTo_VCChanging(value);
					this.SendPropertyChanging();
					this._DateDisabilityTo_VC = value;
					this.SendPropertyChanged("DateDisabilityTo_VC");
					this.OnDateDisabilityTo_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastWorked_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateLastWorked_VC
		{
			get
			{
				return this._DateLastWorked_VC;
			}
			set
			{
				if ((this._DateLastWorked_VC != value))
				{
					this.OnDateLastWorked_VCChanging(value);
					this.SendPropertyChanging();
					this._DateLastWorked_VC = value;
					this.SendPropertyChanged("DateLastWorked_VC");
					this.OnDateLastWorked_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateWorkReturn_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateWorkReturn_VC
		{
			get
			{
				return this._DateWorkReturn_VC;
			}
			set
			{
				if ((this._DateWorkReturn_VC != value))
				{
					this.OnDateWorkReturn_VCChanging(value);
					this.SendPropertyChanging();
					this._DateWorkReturn_VC = value;
					this.SendPropertyChanged("DateWorkReturn_VC");
					this.OnDateWorkReturn_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRelatedHospitalizationAdmission_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateRelatedHospitalizationAdmission_VC
		{
			get
			{
				return this._DateRelatedHospitalizationAdmission_VC;
			}
			set
			{
				if ((this._DateRelatedHospitalizationAdmission_VC != value))
				{
					this.OnDateRelatedHospitalizationAdmission_VCChanging(value);
					this.SendPropertyChanging();
					this._DateRelatedHospitalizationAdmission_VC = value;
					this.SendPropertyChanged("DateRelatedHospitalizationAdmission_VC");
					this.OnDateRelatedHospitalizationAdmission_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRelatedHospitalizationDischarge_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateRelatedHospitalizationDischarge_VC
		{
			get
			{
				return this._DateRelatedHospitalizationDischarge_VC;
			}
			set
			{
				if ((this._DateRelatedHospitalizationDischarge_VC != value))
				{
					this.OnDateRelatedHospitalizationDischarge_VCChanging(value);
					this.SendPropertyChanging();
					this._DateRelatedHospitalizationDischarge_VC = value;
					this.SendPropertyChanged("DateRelatedHospitalizationDischarge_VC");
					this.OnDateRelatedHospitalizationDischarge_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAssumedOrRelinquishedCareStart_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateAssumedOrRelinquishedCareStart_VC
		{
			get
			{
				return this._DateAssumedOrRelinquishedCareStart_VC;
			}
			set
			{
				if ((this._DateAssumedOrRelinquishedCareStart_VC != value))
				{
					this.OnDateAssumedOrRelinquishedCareStart_VCChanging(value);
					this.SendPropertyChanging();
					this._DateAssumedOrRelinquishedCareStart_VC = value;
					this.SendPropertyChanged("DateAssumedOrRelinquishedCareStart_VC");
					this.OnDateAssumedOrRelinquishedCareStart_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAssumedOrRelinquishedCareEnd_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateAssumedOrRelinquishedCareEnd_VC
		{
			get
			{
				return this._DateAssumedOrRelinquishedCareEnd_VC;
			}
			set
			{
				if ((this._DateAssumedOrRelinquishedCareEnd_VC != value))
				{
					this.OnDateAssumedOrRelinquishedCareEnd_VCChanging(value);
					this.SendPropertyChanging();
					this._DateAssumedOrRelinquishedCareEnd_VC = value;
					this.SendPropertyChanged("DateAssumedOrRelinquishedCareEnd_VC");
					this.OnDateAssumedOrRelinquishedCareEnd_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePropertyAndCasualtyDateOfFirstContact_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DatePropertyAndCasualtyDateOfFirstContact_VC
		{
			get
			{
				return this._DatePropertyAndCasualtyDateOfFirstContact_VC;
			}
			set
			{
				if ((this._DatePropertyAndCasualtyDateOfFirstContact_VC != value))
				{
					this.OnDatePropertyAndCasualtyDateOfFirstContact_VCChanging(value);
					this.SendPropertyChanging();
					this._DatePropertyAndCasualtyDateOfFirstContact_VC = value;
					this.SendPropertyChanged("DatePropertyAndCasualtyDateOfFirstContact_VC");
					this.OnDatePropertyAndCasualtyDateOfFirstContact_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRepricerReceived_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DateRepricerReceived_VC
		{
			get
			{
				return this._DateRepricerReceived_VC;
			}
			set
			{
				if ((this._DateRepricerReceived_VC != value))
				{
					this.OnDateRepricerReceived_VCChanging(value);
					this.SendPropertyChanging();
					this._DateRepricerReceived_VC = value;
					this.SendPropertyChanged("DateRepricerReceived_VC");
					this.OnDateRepricerReceived_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractTypeCode_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ContractTypeCode_VC
		{
			get
			{
				return this._ContractTypeCode_VC;
			}
			set
			{
				if ((this._ContractTypeCode_VC != value))
				{
					this.OnContractTypeCode_VCChanging(value);
					this.SendPropertyChanging();
					this._ContractTypeCode_VC = value;
					this.SendPropertyChanged("ContractTypeCode_VC");
					this.OnContractTypeCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractAmount_VC", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string ContractAmount_VC
		{
			get
			{
				return this._ContractAmount_VC;
			}
			set
			{
				if ((this._ContractAmount_VC != value))
				{
					this.OnContractAmount_VCChanging(value);
					this.SendPropertyChanging();
					this._ContractAmount_VC = value;
					this.SendPropertyChanged("ContractAmount_VC");
					this.OnContractAmount_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractPercentage_VC", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string ContractPercentage_VC
		{
			get
			{
				return this._ContractPercentage_VC;
			}
			set
			{
				if ((this._ContractPercentage_VC != value))
				{
					this.OnContractPercentage_VCChanging(value);
					this.SendPropertyChanging();
					this._ContractPercentage_VC = value;
					this.SendPropertyChanged("ContractPercentage_VC");
					this.OnContractPercentage_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractCode_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContractCode_VC
		{
			get
			{
				return this._ContractCode_VC;
			}
			set
			{
				if ((this._ContractCode_VC != value))
				{
					this.OnContractCode_VCChanging(value);
					this.SendPropertyChanging();
					this._ContractCode_VC = value;
					this.SendPropertyChanged("ContractCode_VC");
					this.OnContractCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermsDiscountPercentage_VC", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string TermsDiscountPercentage_VC
		{
			get
			{
				return this._TermsDiscountPercentage_VC;
			}
			set
			{
				if ((this._TermsDiscountPercentage_VC != value))
				{
					this.OnTermsDiscountPercentage_VCChanging(value);
					this.SendPropertyChanging();
					this._TermsDiscountPercentage_VC = value;
					this.SendPropertyChanged("TermsDiscountPercentage_VC");
					this.OnTermsDiscountPercentage_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractVersionIdentifier_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ContractVersionIdentifier_VC
		{
			get
			{
				return this._ContractVersionIdentifier_VC;
			}
			set
			{
				if ((this._ContractVersionIdentifier_VC != value))
				{
					this.OnContractVersionIdentifier_VCChanging(value);
					this.SendPropertyChanging();
					this._ContractVersionIdentifier_VC = value;
					this.SendPropertyChanged("ContractVersionIdentifier_VC");
					this.OnContractVersionIdentifier_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAmountPaid_VC", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string PatientAmountPaid_VC
		{
			get
			{
				return this._PatientAmountPaid_VC;
			}
			set
			{
				if ((this._PatientAmountPaid_VC != value))
				{
					this.OnPatientAmountPaid_VCChanging(value);
					this.SendPropertyChanging();
					this._PatientAmountPaid_VC = value;
					this.SendPropertyChanged("PatientAmountPaid_VC");
					this.OnPatientAmountPaid_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteText_VC", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string NoteText_VC
		{
			get
			{
				return this._NoteText_VC;
			}
			set
			{
				if ((this._NoteText_VC != value))
				{
					this.OnNoteText_VCChanging(value);
					this.SendPropertyChanging();
					this._NoteText_VC = value;
					this.SendPropertyChanged("NoteText_VC");
					this.OnNoteText_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeboundIndicator_BT", DbType="Bit NOT NULL")]
		public bool HomeboundIndicator_BT
		{
			get
			{
				return this._HomeboundIndicator_BT;
			}
			set
			{
				if ((this._HomeboundIndicator_BT != value))
				{
					this.OnHomeboundIndicator_BTChanging(value);
					this.SendPropertyChanging();
					this._HomeboundIndicator_BT = value;
					this.SendPropertyChanged("HomeboundIndicator_BT");
					this.OnHomeboundIndicator_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutputPatientSignatureSourceCode_BT", DbType="Bit NOT NULL")]
		public bool OutputPatientSignatureSourceCode_BT
		{
			get
			{
				return this._OutputPatientSignatureSourceCode_BT;
			}
			set
			{
				if ((this._OutputPatientSignatureSourceCode_BT != value))
				{
					this.OnOutputPatientSignatureSourceCode_BTChanging(value);
					this.SendPropertyChanging();
					this._OutputPatientSignatureSourceCode_BT = value;
					this.SendPropertyChanged("OutputPatientSignatureSourceCode_BT");
					this.OnOutputPatientSignatureSourceCode_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientConditionCode_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PatientConditionCode_VC
		{
			get
			{
				return this._PatientConditionCode_VC;
			}
			set
			{
				if ((this._PatientConditionCode_VC != value))
				{
					this.OnPatientConditionCode_VCChanging(value);
					this.SendPropertyChanging();
					this._PatientConditionCode_VC = value;
					this.SendPropertyChanged("PatientConditionCode_VC");
					this.OnPatientConditionCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpinalManipulationPatientConditionCode_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SpinalManipulationPatientConditionCode_VC
		{
			get
			{
				return this._SpinalManipulationPatientConditionCode_VC;
			}
			set
			{
				if ((this._SpinalManipulationPatientConditionCode_VC != value))
				{
					this.OnSpinalManipulationPatientConditionCode_VCChanging(value);
					this.SendPropertyChanging();
					this._SpinalManipulationPatientConditionCode_VC = value;
					this.SendPropertyChanged("SpinalManipulationPatientConditionCode_VC");
					this.OnSpinalManipulationPatientConditionCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpinalManipulationPatientConditionDescription1_VC", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string SpinalManipulationPatientConditionDescription1_VC
		{
			get
			{
				return this._SpinalManipulationPatientConditionDescription1_VC;
			}
			set
			{
				if ((this._SpinalManipulationPatientConditionDescription1_VC != value))
				{
					this.OnSpinalManipulationPatientConditionDescription1_VCChanging(value);
					this.SendPropertyChanging();
					this._SpinalManipulationPatientConditionDescription1_VC = value;
					this.SendPropertyChanged("SpinalManipulationPatientConditionDescription1_VC");
					this.OnSpinalManipulationPatientConditionDescription1_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpinalManipulationPatientConditionDescription2_VC", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string SpinalManipulationPatientConditionDescription2_VC
		{
			get
			{
				return this._SpinalManipulationPatientConditionDescription2_VC;
			}
			set
			{
				if ((this._SpinalManipulationPatientConditionDescription2_VC != value))
				{
					this.OnSpinalManipulationPatientConditionDescription2_VCChanging(value);
					this.SendPropertyChanging();
					this._SpinalManipulationPatientConditionDescription2_VC = value;
					this.SendPropertyChanged("SpinalManipulationPatientConditionDescription2_VC");
					this.OnSpinalManipulationPatientConditionDescription2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPSDTReferralCertificationConditionCodeAppliesIndicator_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string EPSDTReferralCertificationConditionCodeAppliesIndicator_VC
		{
			get
			{
				return this._EPSDTReferralCertificationConditionCodeAppliesIndicator_VC;
			}
			set
			{
				if ((this._EPSDTReferralCertificationConditionCodeAppliesIndicator_VC != value))
				{
					this.OnEPSDTReferralCertificationConditionCodeAppliesIndicator_VCChanging(value);
					this.SendPropertyChanging();
					this._EPSDTReferralCertificationConditionCodeAppliesIndicator_VC = value;
					this.SendPropertyChanged("EPSDTReferralCertificationConditionCodeAppliesIndicator_VC");
					this.OnEPSDTReferralCertificationConditionCodeAppliesIndicator_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPSDTReferralConditionIndicator1_VC", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string EPSDTReferralConditionIndicator1_VC
		{
			get
			{
				return this._EPSDTReferralConditionIndicator1_VC;
			}
			set
			{
				if ((this._EPSDTReferralConditionIndicator1_VC != value))
				{
					this.OnEPSDTReferralConditionIndicator1_VCChanging(value);
					this.SendPropertyChanging();
					this._EPSDTReferralConditionIndicator1_VC = value;
					this.SendPropertyChanged("EPSDTReferralConditionIndicator1_VC");
					this.OnEPSDTReferralConditionIndicator1_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPSDTReferralConditionIndicator2_VC", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string EPSDTReferralConditionIndicator2_VC
		{
			get
			{
				return this._EPSDTReferralConditionIndicator2_VC;
			}
			set
			{
				if ((this._EPSDTReferralConditionIndicator2_VC != value))
				{
					this.OnEPSDTReferralConditionIndicator2_VCChanging(value);
					this.SendPropertyChanging();
					this._EPSDTReferralConditionIndicator2_VC = value;
					this.SendPropertyChanged("EPSDTReferralConditionIndicator2_VC");
					this.OnEPSDTReferralConditionIndicator2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPSDTReferralConditionIndicator3_VC", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string EPSDTReferralConditionIndicator3_VC
		{
			get
			{
				return this._EPSDTReferralConditionIndicator3_VC;
			}
			set
			{
				if ((this._EPSDTReferralConditionIndicator3_VC != value))
				{
					this.OnEPSDTReferralConditionIndicator3_VCChanging(value);
					this.SendPropertyChanging();
					this._EPSDTReferralConditionIndicator3_VC = value;
					this.SendPropertyChanged("EPSDTReferralConditionIndicator3_VC");
					this.OnEPSDTReferralConditionIndicator3_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnesthesiaRelatedSurgicalProcedure_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string AnesthesiaRelatedSurgicalProcedure_VC
		{
			get
			{
				return this._AnesthesiaRelatedSurgicalProcedure_VC;
			}
			set
			{
				if ((this._AnesthesiaRelatedSurgicalProcedure_VC != value))
				{
					this.OnAnesthesiaRelatedSurgicalProcedure_VCChanging(value);
					this.SendPropertyChanging();
					this._AnesthesiaRelatedSurgicalProcedure_VC = value;
					this.SendPropertyChanged("AnesthesiaRelatedSurgicalProcedure_VC");
					this.OnAnesthesiaRelatedSurgicalProcedure_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnesthesiaRelatedSurgicalProcedure2_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string AnesthesiaRelatedSurgicalProcedure2_VC
		{
			get
			{
				return this._AnesthesiaRelatedSurgicalProcedure2_VC;
			}
			set
			{
				if ((this._AnesthesiaRelatedSurgicalProcedure2_VC != value))
				{
					this.OnAnesthesiaRelatedSurgicalProcedure2_VCChanging(value);
					this.SendPropertyChanging();
					this._AnesthesiaRelatedSurgicalProcedure2_VC = value;
					this.SendPropertyChanged("AnesthesiaRelatedSurgicalProcedure2_VC");
					this.OnAnesthesiaRelatedSurgicalProcedure2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceAuthorizationExceptionCode_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ServiceAuthorizationExceptionCode_VC
		{
			get
			{
				return this._ServiceAuthorizationExceptionCode_VC;
			}
			set
			{
				if ((this._ServiceAuthorizationExceptionCode_VC != value))
				{
					this.OnServiceAuthorizationExceptionCode_VCChanging(value);
					this.SendPropertyChanging();
					this._ServiceAuthorizationExceptionCode_VC = value;
					this.SendPropertyChanged("ServiceAuthorizationExceptionCode_VC");
					this.OnServiceAuthorizationExceptionCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicareSection4081Indicator_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MedicareSection4081Indicator_VC
		{
			get
			{
				return this._MedicareSection4081Indicator_VC;
			}
			set
			{
				if ((this._MedicareSection4081Indicator_VC != value))
				{
					this.OnMedicareSection4081Indicator_VCChanging(value);
					this.SendPropertyChanging();
					this._MedicareSection4081Indicator_VC = value;
					this.SendPropertyChanged("MedicareSection4081Indicator_VC");
					this.OnMedicareSection4081Indicator_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MammographyCertificationNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MammographyCertificationNumber_VC
		{
			get
			{
				return this._MammographyCertificationNumber_VC;
			}
			set
			{
				if ((this._MammographyCertificationNumber_VC != value))
				{
					this.OnMammographyCertificationNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._MammographyCertificationNumber_VC = value;
					this.SendPropertyChanged("MammographyCertificationNumber_VC");
					this.OnMammographyCertificationNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferralNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ReferralNumber_VC
		{
			get
			{
				return this._ReferralNumber_VC;
			}
			set
			{
				if ((this._ReferralNumber_VC != value))
				{
					this.OnReferralNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._ReferralNumber_VC = value;
					this.SendPropertyChanged("ReferralNumber_VC");
					this.OnReferralNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriorAuthorization_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PriorAuthorization_VC
		{
			get
			{
				return this._PriorAuthorization_VC;
			}
			set
			{
				if ((this._PriorAuthorization_VC != value))
				{
					this.OnPriorAuthorization_VCChanging(value);
					this.SendPropertyChanging();
					this._PriorAuthorization_VC = value;
					this.SendPropertyChanged("PriorAuthorization_VC");
					this.OnPriorAuthorization_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerClaimControlNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PayerClaimControlNumber_VC
		{
			get
			{
				return this._PayerClaimControlNumber_VC;
			}
			set
			{
				if ((this._PayerClaimControlNumber_VC != value))
				{
					this.OnPayerClaimControlNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._PayerClaimControlNumber_VC = value;
					this.SendPropertyChanged("PayerClaimControlNumber_VC");
					this.OnPayerClaimControlNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicalLaboratoryImprovementAmendmentNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClinicalLaboratoryImprovementAmendmentNumber_VC
		{
			get
			{
				return this._ClinicalLaboratoryImprovementAmendmentNumber_VC;
			}
			set
			{
				if ((this._ClinicalLaboratoryImprovementAmendmentNumber_VC != value))
				{
					this.OnClinicalLaboratoryImprovementAmendmentNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._ClinicalLaboratoryImprovementAmendmentNumber_VC = value;
					this.SendPropertyChanged("ClinicalLaboratoryImprovementAmendmentNumber_VC");
					this.OnClinicalLaboratoryImprovementAmendmentNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepricedClaimReferenceNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RepricedClaimReferenceNumber_VC
		{
			get
			{
				return this._RepricedClaimReferenceNumber_VC;
			}
			set
			{
				if ((this._RepricedClaimReferenceNumber_VC != value))
				{
					this.OnRepricedClaimReferenceNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._RepricedClaimReferenceNumber_VC = value;
					this.SendPropertyChanged("RepricedClaimReferenceNumber_VC");
					this.OnRepricedClaimReferenceNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjustedRepricedClaimReferenceNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdjustedRepricedClaimReferenceNumber_VC
		{
			get
			{
				return this._AdjustedRepricedClaimReferenceNumber_VC;
			}
			set
			{
				if ((this._AdjustedRepricedClaimReferenceNumber_VC != value))
				{
					this.OnAdjustedRepricedClaimReferenceNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._AdjustedRepricedClaimReferenceNumber_VC = value;
					this.SendPropertyChanged("AdjustedRepricedClaimReferenceNumber_VC");
					this.OnAdjustedRepricedClaimReferenceNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvestigationalDeviceExemptionNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InvestigationalDeviceExemptionNumber_VC
		{
			get
			{
				return this._InvestigationalDeviceExemptionNumber_VC;
			}
			set
			{
				if ((this._InvestigationalDeviceExemptionNumber_VC != value))
				{
					this.OnInvestigationalDeviceExemptionNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._InvestigationalDeviceExemptionNumber_VC = value;
					this.SendPropertyChanged("InvestigationalDeviceExemptionNumber_VC");
					this.OnInvestigationalDeviceExemptionNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueAddedNetworkTraceNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ValueAddedNetworkTraceNumber_VC
		{
			get
			{
				return this._ValueAddedNetworkTraceNumber_VC;
			}
			set
			{
				if ((this._ValueAddedNetworkTraceNumber_VC != value))
				{
					this.OnValueAddedNetworkTraceNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._ValueAddedNetworkTraceNumber_VC = value;
					this.SendPropertyChanged("ValueAddedNetworkTraceNumber_VC");
					this.OnValueAddedNetworkTraceNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicalRecordNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MedicalRecordNumber_VC
		{
			get
			{
				return this._MedicalRecordNumber_VC;
			}
			set
			{
				if ((this._MedicalRecordNumber_VC != value))
				{
					this.OnMedicalRecordNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._MedicalRecordNumber_VC = value;
					this.SendPropertyChanged("MedicalRecordNumber_VC");
					this.OnMedicalRecordNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DemonstrationProjectIdentifier_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DemonstrationProjectIdentifier_VC
		{
			get
			{
				return this._DemonstrationProjectIdentifier_VC;
			}
			set
			{
				if ((this._DemonstrationProjectIdentifier_VC != value))
				{
					this.OnDemonstrationProjectIdentifier_VCChanging(value);
					this.SendPropertyChanging();
					this._DemonstrationProjectIdentifier_VC = value;
					this.SendPropertyChanged("DemonstrationProjectIdentifier_VC");
					this.OnDemonstrationProjectIdentifier_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarePlanOversightNumber_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarePlanOversightNumber_VC
		{
			get
			{
				return this._CarePlanOversightNumber_VC;
			}
			set
			{
				if ((this._CarePlanOversightNumber_VC != value))
				{
					this.OnCarePlanOversightNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._CarePlanOversightNumber_VC = value;
					this.SendPropertyChanged("CarePlanOversightNumber_VC");
					this.OnCarePlanOversightNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservedForLocal19_VC", DbType="VarChar(175)")]
		public string ReservedForLocal19_VC
		{
			get
			{
				return this._ReservedForLocal19_VC;
			}
			set
			{
				if ((this._ReservedForLocal19_VC != value))
				{
					this.OnReservedForLocal19_VCChanging(value);
					this.SendPropertyChanging();
					this._ReservedForLocal19_VC = value;
					this.SendPropertyChanged("ReservedForLocal19_VC");
					this.OnReservedForLocal19_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClaimMedicalBase_T_ClaimMedicalClaimInformation_T", Storage="_ClaimMedicalBase_T", ThisKey="ClaimMedicalBase_ID", OtherKey="ClaimMedicalBase_ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public ClaimMedicalBase_T ClaimMedicalBase_T
		{
			get
			{
				return this._ClaimMedicalBase_T.Entity;
			}
			set
			{
				ClaimMedicalBase_T previousValue = this._ClaimMedicalBase_T.Entity;
				if (((previousValue != value) 
							|| (this._ClaimMedicalBase_T.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClaimMedicalBase_T.Entity = null;
						previousValue.ClaimMedicalClaimInformation_Ts.Remove(this);
					}
					this._ClaimMedicalBase_T.Entity = value;
					if ((value != null))
					{
						value.ClaimMedicalClaimInformation_Ts.Add(this);
						this._ClaimMedicalBase_ID = value.ClaimMedicalBase_ID;
					}
					else
					{
						this._ClaimMedicalBase_ID = default(long);
					}
					this.SendPropertyChanged("ClaimMedicalBase_T");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
